### ISSUE TITLE
zigpy-zboss compatibility with Python 3.12?

### ISSUE THREAD

**Issue by Hedda** [kardia-as/zigpy-zboss#38]
Has anyone checked if [zigpy-zboss](https://github.com/kardia-as/zigpy-zboss) has any issues with Python 3.12 or if it is fully compatible with Python 3.12?

Not tested myself but since had issue with Python 3.11 as per https://github.com/kardia-as/zigpy-zboss/issues/28 thought flag that the Home Assistant 2024.2 release is now shipping with Python 3.12 by default (which is currently the newest major release of the Python programming language):

https://www.home-assistant.io/blog/2024/02/07/release-20242/#shipping-on-a-new-python-version

Preferably testing Home Assistant Operating System (HA OS), alternatively Home Assistant Container and/or Supervised on Debian 12 with Python 3.12.x versions?

https://www.home-assistant.io/installation/#advanced-installation-methods

https://www.home-assistant.io/more-info/unsupported/os/

**Comment by markushx** [comment]
Worked for me on 2024.2.2.
