### ISSUE TITLE
zigpy-cli support?

### ISSUE THREAD

**Issue by Hedda** [kardia-as/zigpy-zboss#4]
Is anything needed for zigpy-cli support other than adding zigpy-zboss as a dependency?

https://github.com/zigpy/zigpy-cli

**Comment by DamKast** [comment]
I opened a PR in the zigpy-cli repo (https://github.com/zigpy/zigpy-cli/pull/40) to add zboss support.
I tested the backup, info and permit feature for now and it is supposed to work with zigpu-zboss v1.1.0.
