### ISSUE TITLE
watchdog compatibility with latest zigpy

### ISSUE THREAD

**Issue by Hedda** [kardia-as/zigpy-zboss#47]
zigpy-zboss radio library for zigpy does not yet seem compatible with the "watchdog" changes that was made to zigpy last year?

See references:

* https://github.com/zigpy/zigpy/pulls?q=is%3Apr+watchdog+is%3Aclosed

and

* https://github.com/zigpy/bellows/pulls?q=is%3Apr+watchdog+is%3Aclosed

PS: Also see puddly's reply in https://github.com/home-assistant/core/pull/114828 indicates that this and adding [unit tests](https://github.com/kardia-as/zigpy-zboss/issues/7) are currently showstoppers.

**Comment by DamKast** [comment]
This has been fixed [here](https://github.com/kardia-as/zigpy-zboss/commit/be32c55f3129edba1dd7148ed40c9f156e7e5139)
