### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by DamKast** [kardia-as/zigpy-zboss#7]
Write unit tests for the zigpy-zboss code.

**Comment by Hedda** [comment]
@DamKast  Any updates on unit tests in this ZBOSS radio library for zigpy?

puddly reply to @e3c6a08b1f15492310b7e2912cc3552b in https://github.com/home-assistant/core/pull/114828 indicate this is currently a showstopper.

Please see the `tests` directory for bellows, zigpy-znp, and zigpy-deconz radio libraries:

https://github.com/zigpy/bellows/tree/dev/tests

https://github.com/zigpy/zigpy-znp/tree/dev/tests

https://github.com/zigpy/zigpy-deconz/tree/dev/tests
